---
title: "Blood donor recruitment prediction"
author: "Timo Asikainen"
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    theme: united
---

# Parameters

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(openxlsx)
library(ggplot2) # # heatmaps etc
#library(reshape2)
```

GitHub: <https://github.com/FRCBS/donor-recruitment-prediction/blob/main/src/blood-donor-recruitment-prediction.Rmd>

```{r parameters}
# Notes from meeting with Mart and Amber (2 Oct 2024)
# DonationPlaceType: Mobile vs Office/other
# 2000 -> 2008: first year of data
# country-specific parameter (?)


# group definitions ie. group tables for new donors
param=list()
param$donation.types = c('Whole Blood (K)','Trombapheresis (T)')

# 2024-08-12 Restrict to whole blood donations to see if there is an effect
param$donation.types = c('Whole Blood (K)')

param$annual.first.time.donors=22080

param$data.file = "/mnt/c/Users/potha01m/data/data_for_Timo/data.rdata"

# Create directory if it does not already exist
dir.create(file.path("../results"),showWarnings = FALSE)
# NB. this command might behave differently depending
#on if you running from console or Rmd.
param$result.file = '../results/data.xlsx'



# These parameters are used to estimate the cumulative donation amounts in the script
# and in the Knitr graphs. All the parameters are exported to the xlsx file.
# These parameters do not affect the exported distribution matrix (distm).

#MP: Changed this...
param$reference.year=2011
param$last.data.year=2023

param$useOfficeMobile = TRUE

# This limit is applied to each group and year combination: if the number of (first-time) donors
# is below the limit, no size data will be exported and the rows will be omitted from the distribution matrix (distm).
# The data will still be included in the age distribution (dista): this data is aggregated in groups of five years.
param$min.group.year.size=30



```

```{r group-definitions}
table.text="
age.lower	age.upper	DonationPlaceType	Sex	BloodGroup	Multiplier	MaximumAge	Name
0	25	Office	Male	-O-	1	70	Male Office 0-25
25	40	Office	Male	-O-	1	70	Male Office 25-40
40	100	Office	Male	-O-	1	70	Male Office 40-100
0	25	Office	Female	-O-	1	70	Female Office 0-25
25	40	Office	Female	-O-	1	70	Female Office 25-40
40	100	Office	Female	-O-	1	70	Female Office 40-100
0	25	Mobile	Male	-O-	1	70	Male Mobile 0-25
25	40	Mobile	Male	-O-	1	70	Male Mobile 25-40
40	100	Mobile	Male	-O-	1	70	Male Mobile 40-100
0	25	Mobile	Female	-O-	1	70	Female Mobile 0-25
25	40	Mobile	Female	-O-	1	70	Female Mobile 25-40
40	100	Mobile	Female	-O-	1	70	Female Mobile 40-100
0	100	Office	Male	O-	1	70	Male Office 0-100
0	100	Office	Female	O-	1	70	Female Office 0-100
0	100	Mobile	Male	O-	1	70	Male O- Mobile 0-100
0	100	Mobile	Female	O-	1	70	Female O- Mobile 0-100"
table.text=gsub(" ","¤",table.text)
nd = read.table(header=TRUE,text = table.text)
nd$Name=gsub("¤"," ",nd$Name)

# This is only for Finnish special case and is not used by default
table.text="
age.lower	age.upper	DonationPlaceType	Sex	BloodGroup	Multiplier	MaximumAge	Name
0	25	-Garrison	Male	-O-	1	70	Male <25
25	40	-Garrison	Male	-O-	1	70	Male 25-40
40	100	-Garrison	Male	-O-	1	70	Male 40+
0	30	Garrison	Male	-O-	1	70	Garrison <30
30	100	Garrison	Male	-O-	1	70	Garrion 30+
0	100	*	Male	O-	1	70	Male O-
0	100	*	Female	O-	1	70	Female O-
0	25	*	Female	-O-	0.8	70	Female <25
25	40	*	Female	-O-	1	70	Female 25-40
40	100	*	Female	-O-	1	70	Female 40+"
table.text=gsub(" ","¤",table.text)
nd.garrison = read.table(header=TRUE,text = table.text)
nd.garrison$Name=gsub("¤"," ",nd.garrison$Name)

table.text="age.lower	age.upper	DonationPlaceType	Sex	BloodGroup	Multiplier	MaximumAge	Name
0	100	*	*	O-	1	70	O-
0	100	*	*	-O-	1	70	Other"
gt.oneg = read.table(header=TRUE,text = table.text)

table.text="age.lower	age.upper	DonationPlaceType	Sex	BloodGroup	Multiplier	MaximumAge	Name
0	100	*	Male	*	1	70	Male
0	100	*	Female	*	1	70	Female"
gt.sex = read.table(header=TRUE,text = table.text)
```

# Functions

```{r}
# Group table (gt) is the structure defined in Excel that contains the information on how the
# donation base (currently first-time donors) is to be split into groups for predicting
# the donations over years.
# data.param = spair
# gt = ed
processGroupTable = function(data.param,gt) {
  # The list of group data, each consisting data, distm, m, dista, to be returned
  res=list()
  # ldata will be a list containing the group specific portion of the entire input data (data.param)
  ldata = list()
  
  is.existing = FALSE
  data.full = data
  if ('TimeSincePrevious' %in% colnames(gt)) {
    is.existing = TRUE
    data0=data.param
  } else {
    # Remove the repeat donors just to be sure at this point, if processing new donors
    data0=data.param[data.param$ord==1,]
  }
  
  check.column = function(vec,rule) {
    # vec is a column from a data tale
    # rule is a rule such as '-O-' as specified in Excel or other form of group definition
    # return value is a Boolean vector along vec, TRUE if the element matches the rule
    # Negation can be handled as a final stage, once the non-negated version of the rule has been processed
    if (rule == '*')
      return(rep(TRUE,length(vec)))
    
    parts=strsplit(rule,',')[[1]]
    wh = which(parts=='#NA')
    
    na.included = FALSE
    if (length(wh) > 0) {
      parts = parts[-wh]
      na.inluded = TRUE
    }
    
    negated = grepl('^-',rule)
    if (negated)
      parts[1] = sub('-','',parts[1])
    
    res = (vec %in% parts) 
    if (na.included)
      res = res | is.na(vec)
    
    if (negated) {
      return(!res)
    } else {
      return(res)
    }
  }

  for (r in 1:dim(gt)[1]) {
    # Filter the data as defined by the criteria in the table (parameter gt)
    data=data0
    
    # The donor data is structured differently
    if (!is.existing && 'type' %in% colnames(data))
      data=data[data$type=='donation' & data$ord==1,]
    
    data=data[data$age>gt[r,'age.lower']&data$age<=gt[r,'age.upper'],]
    
    if (is.existing) {
      cvalue = gt[r,'TimeSincePrevious']
      data = data[check.column(data$grDiff,cvalue),]
    }
    
    if (is.existing) {
      cvalue = gt[r,'Donations']
      data=data[check.column(data$grFreq,cvalue),]
    }
    
    # nb! This block has been copied, although it could be a function
    # But would data be actually copied to the function?
    cvalue = gt[r,'DonationPlaceType']
    data = data[check.column(data$DonationPlaceType,cvalue),]

    cvalue = gt[r,'Sex']
    data = data[check.column(data$Sex,cvalue),]

    cvalue = gt[r,'BloodGroup']
    data = data[check.column(data$BloodGroup,cvalue),]
    
    ldata[[r]] = data
  }
  # nb! Must remove the overlap from data.
  # And maybe add an additional remainder class for numids included in data but not
  # in included in any of the groups.
  
  if (is.existing) {
    cdata=cbind(gr=1,ldata[[1]][,c('numid','date')])
    for (i in 2:length(ldata)) {
      cdata=rbind(cdata,cbind(gr=i,ldata[[i]][,c('numid','date')]))
    }
    
    # columns in last.group: numid, date, gr
    last.group = cdata %>%
      group_by(numid) %>%
      summarise(date=max(date),.groups='drop') %>%
      inner_join(cdata,join_by(numid,date))
      # nb! Maybe still summarise further to remove possible duplicated from the definitions
  
    # data.tmp = group$data[group$data$numid %in% last.group$numid[last.group$gr==k],c('date','numid','ord')]
    # Edit the data under the result to match the last groups
  } # if-is.existing
  
  for (i in 1:dim(gt)[1]) {
    if (is.existing) {
      n0 = dim(ldata[[i]])[1]
      ldata[[i]] = ldata[[i]][ldata[[i]]$numid %in% last.group$numid[last.group$gr==i],]
      n1 = dim(ldata[[i]])[1]
      print(paste(i,':',n0,'->',n1))
    }
    
    distm = distributionMatrix2(ldata[[i]],data.param)
    m = estimate.predict(distm,ref.year=param$reference.year,last.data.year=param$last.data.year)
    dista = getAgeDistributionMatrix(ldata[[i]])
    
    res[[i]] = list(data=ldata[[i]],distm=distm,m=m,dista=dista)
  }

  return(res)
}

cumulativeToDensity = function(dist) {
  return((c(dist,0)-c(0,dist))[1:length(dist)])
}
```

```{r}
computeDonationAmounts = function(resl,gtl,years.ahead=55,first.predicted.year=2023,is.existing=FALSE,by.age=FALSE,total.donations=0) {
  if (is.existing) {
    cdata=cbind(gr=1,resl[[1]]$data[,c('numid','date')])
    for (i in 2:length(resl)) {
      cdata=rbind(cdata,cbind(gr=i,resl[[i]]$data[,c('numid','date')]))
    }
    
    last.group = cdata %>%
      group_by(numid) %>%
      summarise(date=max(date),.groups='drop') %>%
      inner_join(cdata,join_by(numid,date))
  }
  
  data.sum = 0
  for (k in 1:length(resl)) {
    data.sum = data.sum + table(year(resl[[k]]$data$date))[as.character(first.predicted.year-1)]
  }
  
  for (k in 1:length(resl)) {
    group=resl[[k]]
    
    max.age=gtl[k,'MaximumAge']
    m=group$m
    new=data.frame(x=1:years.ahead, sqrt.x=(1:years.ahead)^0.5)
    pred = predict(m, new, interval = "prediction")
    pv = as.vector(pred[,1])
    
    # There are the expected numbers of donations per year
    # This includes conversion from cumulative values to densities; could use the function as well
    # pp ~ per person
    pred.donations.pp=(c(pv,0)-c(0,pv))[1:length(pv)]
    
    # 2024-08-09 The predictions may become negative, so set them to 0 here
    pred.donations.pp[pred.donations.pp<0] = 0
    
    group$dista[is.na(group$dista)]=1
    dista=group$dista[,'2020'] # nb hard coded
    dista=cumulativeToDensity(dista)
  
    if (is.existing) {
      # data.tmp = group$data[group$data$numid %in% last.group[last.group$gr==k,'numid'],]
      data.tmp = group$data[group$data$numid %in% last.group$numid[last.group$gr==k],c('date','numid','ord')]
      # Here the predictions are based on the last observation.
      # Does this make sense? Any observation would seem to work.
      dlast = data.tmp %>%
        mutate(year=year(date)) %>%
        filter(year<first.predicted.year) %>%
        group_by(numid) %>%
        summarise(ord = max(ord),.groups='drop') %>%
        # nb! spair is used here
        inner_join(spair[,c('numid','ord','age','date','year0')],join_by(numid,ord==ord)) %>%
        mutate(year=year(date),age=as.integer(age)) %>%
        group_by(year,year0,age) %>%
        summarise(n=n(),.groups='drop')
        # -> year, age, n (number of donors)

        # rownames(estimates)=apply(t(matrix(dlast[1:2,])),1,FUN=function(x) {return(paste(x,collapse='*'))})
    }
    
    sumn=0
     # iterate over the initial ages in the group
    donation.amounts = matrix(0,ncol=years.ahead,nrow=length(rownames(group$dista)))
    colnames(donation.amounts)=1:years.ahead
    rownames(donation.amounts)=rownames(group$dista)
    for (i in 1:length(rownames(group$dista))) {
      n=rownames(group$dista)[i]
      years.active=max.age-as.integer(n)
      
      if (years.active < 0)
        # This case occurs when the age group is over the maximum age and thus has no active years
        break
      
      # in case of old donors, must start from a later position in pred.donations.pp
      # but still place the first values in the beginning, eg. project them for 2024 etc.
      # Need to compute the dlast table here
      annual.donation.densities = pred.donations.pp # 
      annual.donation.densities[(years.active+1):years.ahead]=0
      
      # nb! hard coded data again: use the number of donors from year 2003
      if (is.existing) {
        # ... contents has been removed from this version
      } else {
        # The case for new donors: simple and easy
        vmult = 1
        if (!is.null(total.donations) && total.donations > 0) 
          vmult = as.numeric(total.donations) / as.numeric(data.sum)
      
        donation.amounts[i,] = vmult * annual.donation.densities *
          as.integer(table(year(group$data$date))[as.character(first.predicted.year-1)]) * dista[i]
      }
    } # for (i in 1:length(rownames(group$dista))) # groups
    
    if (by.age)
      resl[[k]]$donation.amounts = donation.amounts
    else
      resl[[k]]$donation.amounts = colSums(donation.amounts)
  }
  
  return(resl)
}
```

```{r}
getDensity = function(distm) {
  distm.m1=cbind(matrix(0,ncol=1,nrow=dim(distm)[1]),distm[,1:(dim(distm)[2]-1)])   
  return(distm-distm.m1)
}

plotDistibutionMatrix = function(distm,diff=FALSE,skip.years=1,main='') {
  if (!diff) {
    colfunc <- colorRampPalette(c("white","green"))
    cut.lower  = min(distm,na.rm=TRUE)-0.1
    cut.higher = max(distm,na.rm=TRUE)+0.1
  } else {
    colfunc <- colorRampPalette(c('red','white','blue'))
    abs.extreme = max(abs(distm),na.rm=TRUE) + 0.1
    cut.lower = -abs.extreme
    cut.higher = abs.extreme
    # print(paste(cut.lower,cut.higher))
  }
  
  # fill.cut=cut(value,seq(min(distm,na.rm=TRUE)-0.1,max(distm,na.rm=TRUE)+0.1,length.out=50))
  fill.seq = seq(cut.lower, cut.higher, length.out = 51)
  # indexing: the skip.years first lines are removed to counter for the effect of pre-2000 donors
  p=ggplot(melt(t(distm[(1+skip.years):dim(distm)[1],])), aes(Var1, Var2, fill=value, label=round(value, 1))) + # cut(value,fill.seq)
    geom_tile()
    if (diff)
      p = p + scale_fill_gradient2(midpoint = 0, low = "red", mid = "white", high = "blue") 
    else
      p = p + scale_fill_gradient2(low = "white", high='green')
    p = p + geom_text(color="black") + 
      guides(fill="none") +
      xlab('time since first donation') +
      ylab('year of first donation') + 
      labs(title=main) + 
      scale_y_reverse()
  p
}
```

# Processing

id.map[donationdata\$donation\$releaseID,'numid']

```{r load-and-preprocess-data}
# Load the data and process it for the purposes of both the 1st time donor analysis 
# and the resilience of the donor base.
start.time <- Sys.time()

if (!exists('load.ready'))
  load.ready = 0

if (!is.null(load.ready) && load.ready != 1) {
  file <- param$data.file
  load(file = file)
  
  # Convert the cumbersome releaseID's to numeric values
  # Each data kind (donation, referral, donor) has its own series so that the values do not overlap for small datasets
  charid=unique(donationdata$donor$releaseID)
  id.map = data.frame(charid=charid,numid=1:length(charid))
  rownames(id.map)=id.map$charid
  
  donationdata$donation$numid=id.map[donationdata$donation$releaseID,'numid']
  donationdata$donor$numid=id.map[donationdata$donor$releaseID,'numid']

  # Remove references to referral and contact data to enable analysis without the
  # related donationdata list memebers.
  # These data are not currently used anyway in the actual analysis.
  # donationdata$deferral$numid=id.map[donationdata$deferral$releaseID,'numid']
  # donationdata$contact$numid=id.map[donationdata$contact$releaseID,'numid']
  
  donationdata$donation$rowid=1e7+as.integer(rownames(donationdata$donation))
  donationdata$donor$rowid=2e5+as.integer(rownames(donationdata$donor))
  # donationdata$deferral$rowid=3e7+as.integer(rownames(donationdata$deferral))
  # donationdata$contact$rowid=4e8+as.integer(rownames(donationdata$contact))
  
  # levels(donationdata$donation$BloodDonationTypeKey)
  # [1] "First Time Donor Sample (Z)"     "Kokoveri/Tetanus (R)"           
  # [3] "KV-valmiste Kokoveri (B)"        "Lisänäyte/virhenäytteenotto (O)"
  # [5] "No Donation (E)"                 "Plasmapheresis (P)"             
  # [7] "Sample (N)"                      "Trombapheresis (T)"             
  # [9] "Whole blood - not testing (H)"   "Whole Blood (K)"
  
  # levels(donationdata$donation$BloodDonationTypeKey)
  # [1] "F (Lifetime deferral)"      "H (Donor Adverse Reaction)" "M (Other)"                 
  # [4] "P (Permanent deferral)"     "R (Restricts production)"   "S (Temporary deferrals)"   
  
  # levels(donationdata$donation$DonationPlaceType)
  # [1] "Garrison" "General" "Learning institution" "Office" "Workplace" 
  
  # Compute simplified versions of donatiosn and deferrals.
  # In the current analysis, deferrals are not actually used so they are omitted from
  # the resulting data set (simple). ord numbers are added to both simplified data sets
  # to facilitate subsequent computations.
  donation.simple = donationdata$donation[donationdata$donation$BloodDonationTypeKey %in% param$donation.types,c('rowid','numid','DonationDate')] %>% 
  	arrange(numid,DonationDate)
  donation.simple$dtEnd = as.Date("2020-01-01") # nb! This is set to NA later
  donation.simple$type = 'donation'
  donation.simple = donation.simple %>% 
    group_by(numid) %>%
    mutate(ord = row_number()) %>%
    ungroup()
  colnames(donation.simple)=c('rowid','numid','date','dtEnd','type','ord')
  
  include.deferrals = FALSE
  if (include.deferrals) {
    deferral.simple = donationdata$deferral[,c('rowid','numid','DeferralStartDate','DeferralEndDate')] %>% 
    	arrange(numid,DeferralStartDate)
    deferral.simple$type = 'deferral'
    deferral.simple = deferral.simple %>% 
      group_by(numid) %>%
      mutate(ord = row_number()) %>%
      ungroup()
    colnames(deferral.simple)=c('rowid','numid','date','dtEnd','type','ord')
    
    # combine the simple data sets: donations and deferrals
    simple = rbind(donation.simple,deferral.simple) %>%
    	arrange(numid,ord)
    simple[simple$type=='donation','dtEnd']=NA
  } else {
    simple = donation.simple
  }
  
  # add a rather precise age for each event
  simple = left_join(simple,donationdata$donor[,c('numid','DateOfBirth','Sex','BloodGroup')],by='numid')
  simple$age= as.numeric(difftime(simple$date,simple$DateOfBirth),unit="weeks")/52.25
  # similarly add the donation place (nb! this could have extracted originally from the donation data)
  simple=inner_join(simple,donationdata$donation[,c('rowid','DonationPlaceType')],join_by(rowid))
  
  # 2024-10-09 Convert the other donation places than 
  if (param$useOfficeMobile) {
    simple$DonationPlaceType = as.character(simple$DonationPlaceType)
    simple$DonationPlaceType[simple$DonationPlaceType!='Office'] = 'Mobile'
  }
  
  # Combine the simple data set with itself to get the links between events; next event in this case
  spair = left_join(simple[simple$type=='donation',c('numid','date','ord')],simple[,c('rowid','numid','date','DateOfBirth','Sex','BloodGroup','DonationPlaceType','age')],join_by(numid,closest(x$date<y$date))) %>%
  	arrange(numid,date.x)
  spair$diff = spair$date.y - spair$date.x
  
  # nb! The hasNext data is not used in this script (except in the end), and this produces wrong results anyway.
  # spair$hasNext = (!is.na(spair$date.y))+0
  spair$firstTime = (spair$ord==1)+0
  
  # Add the date of first donation to facilitate analysis (date0)
  spair = inner_join(spair,simple[simple$type=='donation'&simple$ord==1,c('numid','date')],join_by(numid)) %>%
  	arrange(numid,date.x)
  colnames(spair)[dim(spair)[2]]='date0'
  spair$year0 = year(spair$date0)
  spair$year0Gr=spair$year0-(spair$year0 %% 5)

  spair$ord=spair$ord+1
  wh=is.na(spair$date.y)
  spair$date.y[wh]=spair$date0[wh]
  spair$ord[wh]=1
  
  spair=spair[,-which('date.x'==colnames(spair))]
  colnames(spair)[which('date.y'==colnames(spair))]='date'
  
  spair$grFreq=cut(spair$ord,breaks=c(0,1,5,20,1000))
  levels(spair$grFreq)=c('1st','2-5','6-20','20+')
  
  # Classify donations based on the time elapsed since the previous donation
  spair$grDiff=cut(as.integer(spair$diff),breaks=c(0,90,180,2*365,100*365))
  levels(spair$grDiff)=c('<3mo','3-6mo','<2y','2+y')
  # spair$grDiff = reorder(spair$grDiff,spair$grDiff,levels=rev(c('<3mo','3-6mo','<2y','2+y')))
  # reorder the factor in order to make to make the ordering to be from least active to most active
  spair$grDiff = fct_rev(spair$grDiff)
  
  spair = arrange(spair,numid,ord)
  
  # There are unfortunately some doubles in the data
  # Here we try to get first time data in place, although it is best not to use it maybe
  wh=which(spair$ord==1)
  spair[wh,'firstTime']=1
  replaced=unique(spair[wh,])
  replaced[,c("rowid","numid","date","ord","DateOfBirth","Sex","BloodGroup","age","DonationPlaceType")]=
    simple[simple$numid %in% spair$numid[wh] & simple$ord==1,c("rowid","numid","date","ord","DateOfBirth","Sex","BloodGroup","age","DonationPlaceType")]
  
  spair=spair[-wh,]
  spair=rbind(spair,replaced)
  spair = arrange(spair,numid,ord)
  
  # Compute the number of annual donations from full years
  # This will be used to scale the donation amounts later when using numbers from past years
  annual.donations = donation.simple %>%
    mutate(year=year(date)) %>%
    group_by(year) %>%
    summarise(n=n()) %>%
    filter(year<2024) %>%
    data.frame()
  rownames(annual.donations) = annual.donations$year
  
  annual.new.donors = donation.simple %>%
    filter(ord==1) %>%
    mutate(year=year(date)) %>%
    group_by(year) %>%
    summarise(n=n()) %>%
    filter(year<2024) %>%
    data.frame()
  rownames(annual.new.donors) = annual.new.donors$year
  
  load.ready=1
}

end.time <- Sys.time()
time.taken <- end.time - start.time

# Output a simple measure of the execution time
time.taken

# Time difference of 2.483805 mins
```

```{r}
# This chunk is related to the distribution of age of first donation
# Can be computed separately for different groups
# Ages are grouped in groups of five years (eg. 15-19, 20-24 etc.)
getAgeDistributionMatrix = function(data) {
  # The two out-commented conditions on the following row are unnecessary at this point (at least they should be)
  # Restricting to first time donors should be done in the first stage, if at all
  
  # nb! hard coded
  byAgeYear=data[year(data$date)>=2003,c('age','date')] # data$type=='donation'&data$ord==1&
  stats=byAgeYear %>%
    mutate(year=year(date),age=as.integer(age)) %>%
    mutate(year=year-(year %% 5)) %>%
    group_by(age,year) %>%
    summarise(n=n(),avgAge=mean(age,na.rm=TRUE),.groups='drop')
  
  mat=pivot_wider(stats[,c('age','year','n')],names_from=year,values_from=n,values_fn=mean)
  m=mat[,2:dim(mat)[2]]
  ptbl=sweep(m,2,colSums(m,na.rm=TRUE),`/`)

    ctbl=apply(ptbl,2,cumsum)
  p2=cbind(mat[,1],ctbl)
  wh=which(is.na(p2$age))
  if (length(wh) > 0) {
    wh0=min(wh)
    p2=p2[1:(wh0-1),]
  }
  rownames(p2)=p2$age
  return(p2)
}

# This functon creates the plot but is not actually specific to cumulative distributions
plotAgeDistributionMatrix = function(data,years=17:65,main='') {
  plot(x=NULL,t='n',xaxt='n',xlim=c(min(data$age),max(data$age)),ylim=c(0,1.1),
       xlab='age at first donation',ylab='cumulative proportion of donors up to age',main=main)
  axis(1,at=years,labels=years)
  for (i in 2:dim(data)[2]) {
    lines(years,data[as.character(years),i],col=i+1,lwd=3)
  }
  legend('bottomright',legend=colnames(data)[2:dim(data)[2]],fill=1+2:dim(data)[2])
}
```

```{r}
# nb: ref.year is the row that is used for prediction; if data begins 2000, this will be year 2003
# distm should be the cumulative distribution matrix
estimate.predict = function(dist,ref.year="2012",last.data.year=2023,years.ahead=55,main='',sub='') {
  # dist = res.nd[[1]]$distm
  ref.year=as.character(ref.year)
  ref.year.numeric = as.integer(ref.year)
  years.to.use = 1 + (as.integer(last.data.year) - ref.year.numeric)
  data=data.frame(y=dist[as.character(ref.year),1:years.to.use],x=1:years.to.use) # dim(dist)[2])
  
  # assume the data follows the square root form
  data$sqrt.x=data$x^0.5
  m=lm(y~x+sqrt.x,data=data)
  
  # Values are predicted here only if the main parameter is given. Otherwise years.ahead remains unused as well
  new=data.frame(x=1:years.ahead,sqrt.x=(1:years.ahead)^0.5)
  pred.w.plim <- predict(m, new, interval = "prediction")
  pred.w.clim <- predict(m, new, interval = "confidence")
  if (main != '') {
    matplot(new$x, cbind(pred.w.clim, pred.w.plim[,-1]),
      lty = c(1,2,2,3,3), type = "l", ylab = "predicted y",main=main,sub=sub)
    points(data$x,data$y)
  }
  
  return(m)
}

plot.estimated = function(nres,gt,bundle=FALSE,years.ahead=55) {
  # nres = res.oneg
  # gt = gt.oneg
  # bundle=TRUE
  
  models=list()
  for (i in 1:length(nres)) {
    group = nres[[i]]
    models[[i]]=estimate.predict(group$distm,
                     main = if (bundle) '' else gt$Name[i],
                     sub=paste('n=',dim(group$data)[1],sep=''))
  }
  
  mean.y = NULL
  
  # Create a plot with all the model estimates if requested
  if (bundle) {
    # nb! should set a reasonable value for the maximum
    plot(x=NULL,type='n',xlim=c(0,55),ylim=c(0,20),ylab='cumulative number of donations',xlab='years since first donation')
    for (i in 1:length(models)) {
      new=data.frame(x=0:years.ahead,sqrt.x=(0:years.ahead)^0.5)
      pred.w.plim <- predict(models[[i]], new, interval = "prediction")
      # pred.w.clim <- predict(models[[i]], new, interval = "confidence")
      lines(new$x, pred.w.plim[,1],lwd=3,col=i+1)
      lines(new$x, pred.w.plim[,2],lwd=1,col=i+1,lty='dashed')
      lines(new$x, pred.w.plim[,3],lwd=1,col=i+1,lty='dashed')
      points(models[[i]]$model$x,models[[i]]$model$y,col=i+1)
      legend('topleft',legend=gt$Name,fill=1+(1:length(models)))
    }
    
    if (length(models)==2) {
      # Plot the proportion as well to enable comparisons
      # Primarily intended to estimate the excess donations by Oneg donors
      lines(models[[1]]$model$x, models[[1]]$model$y/models[[2]]$model$y,lwd=5,lty='dotted')
      mean.y=mean(models[[1]]$model$y/models[[2]]$model$y)
      text(x=30,y=mean.y,labels=paste('ratio =',round(mean.y,3)))
    }
  }
  
  return(mean.y)
}
```

```{r}
# New take on counting the cumulative amounts of donations: utilise pivoting
distributionMatrix2 = function(data.group,data.full,density=FALSE,max.dt=as.Date('2024-04-16'),year.start=2000,year.end=2023) {
  # nb! should implement the remaining parameters
  # The last year should include a full year of donations
  
  # stats will contain the time in years from each donor's first donation to each subsequent donation
  # in years. Example tibble [220,092 × 3]
  stats = data.group %>%
    left_join(data.full[,c('date','ord','numid')],join_by(numid,x$ord<=y$ord)) %>%
    mutate(ydiff = as.integer(as.numeric(date.y-date.x) / 365.25) + 1,
      ydiff.dec=as.numeric(date.y-date.x) / 365.25, 
      cdon = 1 + (ord.y-ord.x)) %>%
    group_by(rowid,ydiff) %>%
    summarise(cdon=max(cdon),.groups='drop')

  # form a grid (donor=rowid x years since first donation), at this point as a list
  # and the average number of cumulative donations as data
  # Example: tibble [625 x 3]
  resgrid = expand.grid(rowid=unique(stats$rowid),ydiff=0:max(stats$ydiff,na.rm=TRUE)) %>%
    inner_join(stats[,c('rowid','ydiff','cdon')],join_by(rowid,closest(y$ydiff<=x$ydiff))) %>%
    inner_join(data.full[,c('rowid','date')],join_by(rowid)) %>%
    mutate(year=year(date)) %>%
    group_by(year,ydiff.x) %>%
    summarise(cdon=mean(cdon),.groups='drop')

  # Convert the result to matrix form
  mat=as.matrix(pivot_wider(resgrid,names_from=ydiff.x,values_from=cdon,values_fn=mean))
  rownames(mat)=mat[,1]
  mat=mat[,2:dim(mat)[2]]

  dmat = getDensity(mat)

  # Fill in possible gaps in the matrix with zeros
  years.ahead=max((year.end-year.start)+1,dim(mat)[2])
  zerom=matrix(0,ncol=years.ahead,nrow=dim(mat)[1])
  zerom[1:dim(mat)[1],1:dim(mat)[2]]=mat
  rownames(zerom)=rownames(mat)
  colnames(zerom)=1:years.ahead
  mat=zerom
  mat.na=is.na(mat)
  mat[is.na(mat)]=0
  mat=t(apply(mat,1,FUN=function(x) cummax(x)))
  
  mat[dmat==0]=NA

  return(mat)
}
```

```{r}
sumDonationAmounts = function(nres,gt,existing=FALSE,years.ahead=55,total.donations=0) {
  dares = computeDonationAmounts(nres,gt,by.age=FALSE,is.existing=existing,total.donations=total.donations)
  dona = matrix(0,ncol=years.ahead,nrow=length(nres))
  for (i in 1:length(nres)) {
    dona[i,] = dares[[i]]$donation.amounts
  }

  if (!existing) {
    m = years.ahead
    cdona = matrix(0,nrow=dim(gt)[1],ncol=2*m)
    for (i in 1:m) {
      cdona[,i:(i+(m-1))] = cdona[,i:(i+(m-1))] + dona
    }
    
    return(cdona[,1:m])
  }
  
  return(dona)
}

plotDonationAmounts = function(dona,gt) {
  dfdona=data.frame(grp=gt$Name,dona)
  pdata=pivot_longer(dfdona,cols=starts_with('X'),names_to='year',names_prefix='X',values_to='donations') %>%
    group_by(grp) %>%
    mutate(year = as.integer(year))
    
  data.frame(pdata) %>%
    ggplot(aes(x = year, y = donations, fill = grp)) +
    geom_area() +     
    theme(legend.position="bottom")
}

# Run this to check actual donation amounts, check here
if (FALSE) {
  donation.simple %>%
    mutate(year=year(date)) %>%
    group_by(year) %>%
    summarise(n=n()) %>%
    filter(year<2024)
}
```

# Results

```{r compute-distributions-groups}
# 2024-08-07 trying the data for existing donors now
#res.ed.old=res.ed
# res.ed=processGroupTable(spair,ed)
res.nd=processGroupTable(simple,nd)
res.oneg=processGroupTable(simple,gt.oneg)
res.sex=processGroupTable(simple,gt.sex)
```

```{r plot-groups}
# 2024-08-08 This draws the plot for each group of both new and existing donors
plot.estimated(res.nd,nd,bundle=FALSE)
# plot.estimated(res.ed,ed,bundle=FALSE)

oneg.ratio=plot.estimated(res.oneg,gt.oneg,bundle=TRUE)
plot.estimated(res.sex,gt.sex,bundle=TRUE)
```

```{r dompute donation amounts}
dona.nd = sumDonationAmounts(res.nd,nd,FALSE,total.donations=param$annual.first.time.donors)

# 22080 is the assumed number of new donors
nd.annual = 22080
# the cumulative annual donations multiplier for new donors
# To be used later in computations specific to Finland
nd.cad.multiplier = max(colSums(dona.nd)) / nd.annual

# dona.ed = sumDonationAmounts(res.ed,ed,TRUE)
```

```{r}
# 2024-08-08
# These are the colourful area charts of the projected donation amounts
# A bonus would be to draw the previous donation amounts at least as ungrouped data.
# Plot the chart for new donors
plotDonationAmounts(dona.nd,nd)

# Plot the chart for existing donors
# plotDonationAmounts(dona.ed,ed)

# Compbined plot with new and existing donors
# plotDonationAmounts(rbind(colSums(dona.nd),colSums(dona.ed)),data.frame(Name=c('new donors','existing donors')))
```

```{r}
ord.last = spair %>%
  group_by(numid) %>%
  summarise(ord.max=max(ord),hasNext=0)

spair2 = spair %>%
  left_join(ord.last,join_by(numid,ord==ord.max),suffix=c('.old',''))
spair2$hasNext=is.na(spair2$hasNext)+0

activity.stats = spair2 %>%
	group_by(ord) %>%
	summarise(n=n(),prop=mean(hasNext,na.rm=TRUE),delay=mean(diff,na.rm=TRUE),.groups='drop') %>%
  filter(n >= param$min.group.year.size)

activity.stats$ord = activity.stats$ord-1
activity.stats = activity.stats[activity.stats$ord>0,]
```

# Export

```{r}
if (FALSE) {
  gt = nd
  res = res.nd
  filename = param$result.file
}

# Function to export the data
# 
exportSummary = function(gt, res, filename) {
  sheets = list()
  
  sheet.name = 'activity-stats'
  sheets[[sheet.name]] = activity.stats
  
  sheet.name = paste('parameters')
  sheets[[sheet.name]] = data.frame(param)
  
  for (i in 1:length(gt)) {
    grp = res[[i]]
    grp.info = gt[i,]
    
    sheet.name = paste(grp.info$Name,'definition')
    sheets[[sheet.name]] = grp.info
    
    sheet.name = paste(grp.info$Name,'sizes')
    sizes = grp$data %>%
      mutate(year=year(date)) %>%
      group_by(year) %>%
      summarise(n=n())
    
    valid.years = sizes$year[sizes$n>=param$min.group.year.size]
    sheets[[sheet.name]] = sizes[sizes$year %in% valid.years,]
    
    for (n in names(grp)) {
      if (n %in% c('data','m'))
        next
      
      sheet.name = paste(grp.info$Name,n)
      
      if (n == 'distm') {
        sheets[[sheet.name]] = grp[[n]][as.character(valid.years),]
      } else
        sheets[[sheet.name]] = grp[[n]]
    }
  }
  
  write.xlsx(sheets,filename,rowNames=TRUE)
}
```

```{r}
plot(activity.stats$ord,activity.stats$delay,xlab='number of previous donations',ylab='delay until next donation',type='l',lwd=3,main='Delay till next donation after x previous donations')

plot(activity.stats$ord,activity.stats$prop*100,col='blue',xlim=c(0,150),main='probability of next donation',type='l',lwd=3,xlab='number of previous donations',ylab='probability of next donation (%)')
```

```{r export-summary-data}
exportSummary(nd,res.nd,param$result.file)
```

```{r}
knitr::knit_exit()
```
